# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :unit_tests do
    # add actions here: https://docs.fastlane.tools/actions
    run_tests(
      project: "Task Manager/Task Manager.xcodeproj",
      scheme: "Task Manager",
      configuration: "Debug",
      devices: ["iPhone 14 Pro"]
      )
  end

  desc "Build the app"
  lane :build do
    # add actions here: https://docs.fastlane.tools/actions
    build_app(
      project: "Task Manager/Task Manager.xcodeproj",
      scheme: "Task Manager",
      configuration: "Debug",
      destination: "generic/platform=iOS",
      skip_package_ipa: true,
      skip_package_signing_dossier: true,
      derived_data_path: "build"
      )
  end

  desc "Build and run unit tests"
  lane :build_and_run_unit_tests do
    unit_tests
    build
  end
end
