name: iOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true
      working-directory: Task Manager
        
#    - name: Install Dependencies
#      run: bundle install
#      working-directory: Task Manager
        
    
    - name: Run Tests
      run: bundle exec fastlane ios unit_tests
      working-directory: Task Manager
