name: iOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true
    
    - name: Run Tests
      run: bundle exec fastlane ios unit_tests
